[tool.poetry]
name = "za-identity-number"
version = "0.3.0"
description = "ZA Identity Number checking and validation library"
authors = ["Christo Goosen <christogoosen@gmail.com>"]
license = "MIT"
packages = [
    { include = "za-id-number" },
    { include = "za-id-number/**/*.py" },
]

[tool.poetry.dependencies]
python = "^3.7"
luhn = "^0.2.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.1"
pytest-runner = "^5.2"
bandit = "^1.7.0"
black = "^20.8b1"
flake8 = "^3.8.4"
twine = "^3.3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
